[package]
name = "bkt"
version = "0.1.0"
authors = ["Michael Diamond <dimo414@gmail.com>"]
description = "CLI to cache subprocess invocations"
repository = "http://github.com/dimo414/bkt"
homepage = "http://bkt.rs/"
license = "MIT"
keywords = ["cache", "caching", "subprocess", "cli", "shell"]
categories = ["caching", "command-line-utilities"]
edition = "2018"
include = [
    "**/*.rs",
    "Cargo.*",
    "README.md",
    "LICENSE",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.3", default_features = false, features = ["vec_map"] }
